name: Deliver Tokens To Consumer

on:
  push:
    paths:
      - 'output/**'

jobs:
  # Add a job for every additional consumer/application
  deliver_to_react_application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deliver Platform Deliverable To Application
        uses: andstor/copycat-action@v3
        with:
          # See documentation: https://docs.github.com/en/actions/reference/encrypted-secrets
          # Set the secret in the "src" repository
          personal_token: ${{ secrets.API_TOKEN_GITHUB }}
          # This is the branch that has the code for this article
          src_branch: main
          src_path: output/css/_variables.css
          dst_owner: JingHuangSu1996
          dst_repo_name: jtui
          dst_branch: master
          dst_path: ui.jing-tech.me/tokens/_variables.css
          username: JingHuangSu1996
          email: jing.tech.tw@gmail.com@gmail.com
          commit_message: Update platform deliverable
